cloud.id: 9ae531f57de043f5a07261263736faa5:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyRiMGM4OWUxNmEzMTA0MDNjOTlhNDhhYzdiMGUyNWZkNSRiMjJiM2MyYzZjM2Y0YzZlOWUwYzRmYmIyMTA0Yzc2MQ==
cloud.auth: test-deployment:testDeployment

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.json
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.expand_keys: true

output.elasticsearch:
  hosts: ["https://b22b3c2c6c3f4c6e9e0c4fbb2104c761.us-central1.gcp.cloud.es.io:9243"]